### PR TITLE
update to compassql 0.12.0 and vega-lite 2.0.0-beta.3

### PR DESCRIPTION
**Pull request by vlandham**
I believe I chose the right types in vega-lite for the conversion. 

Right now there is the issue of double imports of vega-util types - but wanted to get this PR started to ensure the changes to types were correct.

### CODE REVIEW

**Comment by vlandham** [comment]
closes #334

**Comment by vlandham** [comment]
i believe these checks will pass when https://github.com/vega/compassql/pull/378 is in and a new version of compassql without the additional types is out.

**Comment by kanitw** [comment]
Just released 0.12.1  -- wanna update package.json and yarn.lock?

**Comment by vlandham** [comment]
updated!

**Comment by kanitw** [comment]
Neat.  thanks!

**Pull request merged**
