### PR TITLE
Utilize new vl-modal directive for bookmarks modal

### PR DESCRIPTION
**Pull request by kadamwhite**
This PR accompanies vega/vega-lite-ui#89

### CODE REVIEW

**Comment by kanitw** [comment]
LGTM  -- feel free to merge when vega/vega-lite-ui#89 is done or ask us to take another look if you have significant pattern change.

**Comment by domoritz** [comment]
Will you redo this for polestar as well?

**Comment by kadamwhite** [comment]
@domoritz yes, once I'm done with the changes to voyager -- it'll reduce pr churn to wait until one complete example is done.

**Comment by domoritz** [comment]
Great.

**Pull request merged**
