### PR TITLE
add ui tests to travis config.

### PR DESCRIPTION
**Pull request by tafsiri**

### CODE REVIEW

**Comment by tafsiri** [comment]
closes #354

**Comment by tafsiri** [comment]
looks like the tests ran and passed.

ping @kanitw

**Comment by kanitw** [comment]
The change in `.travis.yml` looks good to me, but omehow one of the test still fails.

**Comment by tafsiri** [comment]
Thats interesting... one of the runs passes and the other fails but they both run the same tests. Maybe it just needs to be re-run?

**Comment by kanitw** [comment]
Maybe -- I just rebased and force push -- let's see how this goes :)

**Comment by tafsiri** [comment]
worked this time!

**Comment by kanitw** [comment]
Yay!

**Pull request merged**
