### PR TITLE
Use store listener to cause side effect instead.

### PR DESCRIPTION
**Pull request by kanitw**
I think this is definitely an improvement over a hacky solution inside `encoding-pane.ts`.  

That said, if this causes bad effect for loading program state or loading a spec, we could consider other solution.  

In any case, I'll fork from from this branch to work on related views.

### CODE REVIEW

**Comment by vlandham** [comment]
ah. but you are getting error: 

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Connect(BookmarkBase) component.

**Comment by kanitw** [comment]
@vlandham  somehow it's not trigger the same problem anymore

**Comment by vlandham** [comment]
great!

**Comment by kanitw** [comment]
Since it is passing, I will merge it first then, but could you help test https://github.com/vega/voyager/issues/466 and if this does not work we should revise our approach.

**Comment by vlandham** [comment]
sounds good.

**Pull request merged**
