### PR TITLE
Fix the filter range bug

### LINKED ISSUE #708: Cannot type max number in range filter
We shouldn't use onChange event listener

### PR DESCRIPTION
**Pull request by abanh206**
Fix #708

### CODE REVIEW

**Comment by kanitw** [comment]
Not sure why early return solves the problem.  

Can you (1) provide a GIF demonstrating that it solves the problem and (2) give more explanation why?

**Comment by abanh206** [comment]
An early return solves the problem because it stops before the function fires the filter modify action.

[
filterrangefix
](url)

**Comment by kanitw** [comment]
I don't see how this GIF is demonstrating that you are fixing #708.  

>  if the min is 8, the max is 22, we cannot type 25.

Try **typing** the number.

**Comment by kanitw** [comment]
I'll close this PR for now since it's probably not the right fix.  Let's open another one when you have the right fix ready :)

**Pull request closed without merging**
